Update usage of `homebrew`
`homebrew` no longer provides binaries for non-Apple-Silicon Macs. This is a
squash of four commits which severely cut `homebrew` out, removing using it
for `libclang.dylib` entirely.

---

Remove all homebrew taps/packages pre-installed by the runner's image

As `brew` isn't actually the system's package manager, this doesn't break
anything.

Uninstall and reinstall homebrew to remove all packages

Don't use `brew` for LLVM

It takes too long and `brew` is horrific at this point. This now builds it
directly from source before caching it.

Use `ninja` to build `libclang.dylib`, not `make`

In my experience, `ninja` is much faster, so for a project as big as LLVM, it's
worth the extra dependency (compared to the 'standard' dependency of `make`).

Replace installation of `riscv-tools` with solely `riscv-gnu-toolchain`

diff --git a/.github/actions/build-dependencies/action.yml b/.github/actions/build-dependencies/action.yml
--- a/.github/actions/build-dependencies/action.yml
+++ b/.github/actions/build-dependencies/action.yml
@@ -12,7 +12,7 @@ runs:
         sudo apt update -y
 
         # Actually perform the removals
-        sudo apt remove -y "*powershell*" "*nuget*" "*bazel*" "*ansible*" "*terraform*" "*heroku*" "*aws*" azure-cli
+        sudo apt remove -y "*powershell*" "*nuget*" "*bazel*" "*ansible*" "*terraform*" "*heroku*" "*aws*" "*azure*"
         sudo apt remove -y "*yarn*" "*java*" "*kotlin*" "*golang*" "*swift*" "*julia*" "*fortran*" "*android*"
         sudo apt remove -y "*apache2*" "*nginx*" "*firefox*" "*chromium*" "*chrome*" "*edge*"
 
@@ -30,22 +30,42 @@ runs:
         (gem uninstall -aIx) || true
 
         brew analytics off || true
+        rm -rf $(brew --cache)
 
-        for package in \
-          "msbuild" "powershell" "nuget" "bazel" "ansible" "terraform" "heroku" "aws" azure-cli \
-          "nodejs" "npm" "yarn" "java" "kotlin" "golang" "swift" "julia" "fortran" "android" \
-          "apache2" "nginx" "firefox" "chromium" "chrome" "edge" \
-          "qemu" "sql" "texinfo" "imagemagick" \
-        ; do
-          for package in $(brew list --full-name -1 | grep "$package"); do
-            brew uninstall --force "$package" || true
-          done
-        done
+        # The following takes literal _hours_
+        # Instead, we uninstall `homebrew` entirely, before reinstalling it
 
-        # Remove an untrusted tap present for some reason
-        brew untap aws/tap || true
-        # Explicitly uninstall `xcodes` which no longer offers a binary package for Intel macOS
-        brew uninstall --force xcodes || true
+        # # Identify all installed formulae, casks, and available taps
+        # brew install jq || true
+        # PACKAGES=$(brew info --installed --json=v2 | jq -r ".[][] | select(.full_name, .full_token | .)[]")
+        # TAPS=$(brew info --json=v2 | jq -r ".[][].tap" | uniq)
+
+        # # Do not bother removing unused dependencies as we go as we're removing everything anyways
+        # export HOMEBREW_NO_AUTOREMOVE=1
+        # # Remove every pre-installed tap and package
+        # # We remove taps first to start reducing the size of the package list
+        # for tap in $TAPS; do
+        #   brew untap --force "$tap" || true
+        # done
+
+        # for package in $PACKAGES; do
+        #   brew uninstall --force --zap --ignore-dependencies "$package" || true
+        # done
+
+        HOMEBREW_INSTALLER=b41c8e7b3588e2899974119faf3b2a897428648d
+        if [ "${{ runner.arch }}" = "X64" ]; then
+          # This is the last commit before support for non-Apple-Silicon macOS was removed
+          HOMEBREW_INSTALLER=7a133dcc74051ee4efc79467ed215dfedf45aea2
+        fi
+        curl -fsSL https://raw.githubusercontent.com/Homebrew/install/$HOMEBREW_INSTALLER/uninstall.sh > uninstall.sh
+        curl -fsSL https://raw.githubusercontent.com/Homebrew/install/$HOMEBREW_INSTALLER/install.sh > install.sh
+        NONINTERACTIVE=1 sudo /bin/bash uninstall.sh --force
+        rm uninstall.sh
+        NONINTERACTIVE=1 /bin/bash install.sh
+        rm install.sh
+
+        # Clean up the Rust installation made by via `homebrew`'s `rustup` formula
+        rm -rf ~/.rustup ~/.cargo
 
     - name: Install dependencies
       shell: bash
@@ -55,21 +75,18 @@ runs:
         elif [ "$RUNNER_OS" == "Windows" ]; then
           # Use `-gnu` to avoid the installation and licensing headaches of `-msvc`
           rustup set default-host x86_64-pc-windows-gnu
-          choco install llvm protoc
+          choco install protoc llvm
         elif [ "$RUNNER_OS" == "macOS" ]; then
-          brew install protobuf llvm
-          HOMEBREW_PREFIX=$(brew --prefix)
-          [ -d "$HOMEBREW_PREFIX" ]
-
-          # Configure `LIBCLANG_PATH` for `clang-sys`
-          ls $HOMEBREW_PREFIX/opt/llvm/lib | grep "libclang.dylib" # Make sure this installed `libclang`
-          echo "LIBCLANG_PATH=$HOMEBREW_PREFIX/opt/llvm/lib" >> "$GITHUB_ENV"
-
-          # Replace brew rust(up) with rustup
-          brew uninstall --force rustup || true
-          brew uninstall --force rust || true
-          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain stable -y
+          brew update
+          brew install protobuf
         fi
+
+        # Install `rustup`
+        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain stable -y
+
+    - name: Install `libclang.dylib`
+      if: runner.os == 'macOS'
+      uses: ./.github/actions/libclang
 
     - name: Install solc
       shell: bash
@@ -110,6 +127,7 @@ runs:
       run: |
         brew update || true
         brew upgrade || true
+        brew autoremove
         brew cleanup
         rm -rf $(brew --cache)
 
