Tweak CI for if `pallet::hooks` is in use

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -51,15 +51,18 @@ jobs:
       - name: Verify `pallet::hooks` is unused
         shell: bash
         run: |
-          error=0
-          find ./substrate -iname "*.rs" | while read -r file; do
-            hooks=$(grep -F "pallet::hooks" "$file" | grep -v -F "serai-core-pallet: allow" | wc -l)
-            if [ $hooks -ne 0 ]; then
-              echo "\`pallet::hooks\` (without \`serai-core-pallet: allow\`) found in $file"
-              error=1
-            fi
-          done
-          exit $error
+          FAILURES=$(
+            find ./substrate -name "*.rs" | while IFS="\n" read -r file; do
+              hooks=$(grep -F "pallet::hooks" "$file" | grep -v -F "serai-core-pallet: allow" | wc -l || true)
+              if [ $hooks -ne 0 ]; then
+                echo "\`pallet::hooks\` (without \`serai-core-pallet: allow\`) found in $file"
+              fi
+            done
+          )
+          if [ ! "$FAILURES" = "" ]; then
+            echo "$FAILURES"
+            exit 1
+          fi
 
       # Also verify the lockfile isn't dirty
       # This happens when someone edits a Cargo.toml yet doesn't do anything
